### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#10]

**Comment by MarconiS** [comment]
Changing perspective in Remote sensing: from pixel to individual based predictions

**Comment by MarconiS** [comment]
Aim: produce individual trees predictions of traits syndromes, including tree position and crown size/shape. (1) does working on crown level provide better predictions of traits and distribution? (2) why do we care: what can actually be done with individuals that couldn't with pixels [we show some applications]?

**Comment by sjgraves** [comment]
potential 3rd questions (but probably for another paper!): how do trait distributions differ within and among habitat types/land cover types and within and among NEON sites.

**Comment by sjgraves** [comment]
BUT one of the results will be mapped traits at different sites. So while we can't address the 3rd question, we can have some maps as figures and include some discussion points
