### ISSUE TITLE
improve species classification

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#14]

**Comment by MarconiS** [comment]
talking with Ethan, I guess we can make it a next paper. Once we get the individual level predictions the natural evolution is combine the information about species and traits in an intelligent way. The other option would be including it in the first paper, but would take more time and would be more difficult to write. I'd go for a separate (paired) paper

**Comment by sjgraves** [comment]
OK, no species classification in this paper
