### ISSUE TITLE
NLCD types for "new" plots

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#15]
Look up table

**Comment by sjgraves** [comment]
I uploaded some shapefiles to Dropbox that have the new plot extents. In the attribute table there should be a field called class, or something like that, that has a handful of different 2-digit numbers. In this folder is also an image of the NLCD legend that provide the number codes and descriptions of each class.

**Comment by MarconiS** [comment]
we decided to scale up to entire site, we can close this I guess :)
