### ISSUE TITLE
Randomized plots for OSBS and TALL

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#4]

**Comment by sjgraves** [comment]
Generate an attribute table with:
- [ ] habitat type from NLCD

**Comment by MarconiS** [comment]
we were considering with Ethan of not discussing about what is inside the data products, but it could be very valuable to provide data products of trees for flight paths. Basically a .csv with coordinates and traits for every tree in a flight path, for each flight path

**Comment by MarconiS** [comment]
going directly on she, at worst the table of attribute as csv file will be used in the shiny app to make it faster
