### ISSUE TITLE
Where are we publishing?

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#7]

**Comment by sjgraves** [comment]
Some thoughts on where NOT to publish....
Remote Sensing - I think we could easily get it published here, but we may want to aim higher. Does cost a lot because open access is required
Ecological Applications - no, not applied enought
Remote Sensing of Environment - no, not applied enough
Remote Sensing for Ecology and Conservation - no, not applied enough, also costs $$

**Comment by sjgraves** [comment]
List of journals
http://www.aboutgis.com/gis-and-remote-sensing-journal-list-with-impact-factors/

**Comment by MarconiS** [comment]
Ethan this morning was saying that if actually we are kind of the first merging delineation - traits estimation on individual level, given the state of the art of traits related studies (data for no more than 30/45 individuals), we could try aiming Ecology and Evolution, or Methods in Ecology. ITCsegment was published in Methods in Ecology, and does only crown delineation (pretty bad too :D)

**Comment by sjgraves** [comment]
Let's aim for:
Remote Sensing of Environment, and Ecology and Evolution (Sergio will look up)

**Comment by MarconiS** [comment]
MEE or Remote sensing and environment. Let's hope they like it! 🎉
