### ISSUE TITLE
Why are we doing this on an individual tree scale?

### ISSUE THREAD

**Issue by sjgraves** [MarconiS/TraitsOnHeaven#8]
Why does a 1-meter pixel prediction not make sense?
Why go though the extra step of delineating tree crowns in the images?

**Comment by MarconiS** [comment]
(1) boost in predictability
(2) more natural biological unit, comparable with what people do in ecology and with collected data on the field (TRY, BIEN, etc)
(3) allows to identify bags of pixels which can be used to infer noise, materials mixture, and shades

**Comment by sjgraves** [comment]
Let's make a point about working at the individual tree scale in the justification section of the Aim 1 document you sent
